name: Kata-Daniel

on:
  push:
    branches:
      - main

  schedule:
    - cron: "30 20 * * Mon"

jobs:
  integration-e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3

      matrix:
        command:
          - 'gradle clean test -Dcucumber.filter.tags="@LoginErroneo" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'
          - 'gradle clean test -Dcucumber.filter.tags="@LoginSoloUsuario" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'
          - 'gradle clean test -Dcucumber.filter.tags="@LoginVacio" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'
          - 'gradle clean test -Dcucumber.filter.tags="@CreacionDeUsuarioAdmin" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'
          - 'gradle clean test -Dcucumber.filter.tags="@ModificarUsuarioAdmin" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'
          - 'gradle clean test -Dcucumber.filter.tags="@Eliminarusuario" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver '


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar Google Chrome y ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Verificar instalaci贸n
        run: |
          google-chrome --version
          chromedriver --version

      - name: Pre ejecuci贸n
        run: gradle clean clearReports

      - name: Instalaci贸n
        run: gradle clean build -x test

      - name: Ejecuci贸n
        run: ${{ matrix.command }}