name: Kata-Daniel

on:
  push:
    branches:
      - main

  schedule:
    - cron: "30 20 * * Mon"

jobs:
  integration-e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        command:
          - 'gradle clean test -Dcucumber.filter.tags="@LoginErroneo" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'
          - 'gradle clean test -Dcucumber.filter.tags="@LoginSoloUsuario" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'
          - 'gradle clean test -Dcucumber.filter.tags="@LoginVacio" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'
          - 'gradle clean test -Dcucumber.filter.tags="@CreacionDeUsuarioAdmin" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'
          - 'gradle clean test -Dcucumber.filter.tags="@ModificarUsuarioAdmin" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'
          - 'gradle clean test -Dcucumber.filter.tags="@Eliminarusuario" -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Pre ejecución
        run: gradle clean clearReports

      - name: Instalación
        run: gradle clean build -x test

      - name: Ejecución
        run: ${{ matrix.command }}
