name: Kata-Daniel

on:
  push:
    branches:
      - main

  schedule:
    - cron: "30 20 * * Mon"

jobs:
  integration-e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        command:
          - 'gradle clean test -Dcucumber.filter.tags="@LoginErroneo" -Dwebdriver'
          - 'gradle clean test -Dcucumber.filter.tags="@LoginSoloUsuario" -Dwebdriver'
          - 'gradle clean test -Dcucumber.filter.tags="@LoginVacio" -Dwebdriver.chrome'
          - 'gradle clean test -Dcucumber.filter.tags="@CreacionDeUsuarioAdmin" -Dwebdriver'
          - 'gradle clean test -Dcucumber.filter.tags="@ModificarUsuarioAdmin" -Dwebdriver.'
          - 'gradle clean test -Dcucumber.filter.tags="@Eliminarusuario" -Dwebdriver.'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9.]+' | head -1)
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Pre ejecución
        run: gradle clean clearReports

      - name: Instalación
        run: gradle clean build -x test

      - name: Ejecución
        run: ${{ matrix.command }}
