name: Kata-Daniel

on:
  push:
    branches:
      - main

  schedule:
    - cron: "30 20 * * Mon"

jobs:
  integration-e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - 'gradle clean test -Dcucumber.filter.tags="@LoginErroneo"'
          - 'gradle clean test -Dcucumber.filter.tags="@LoginSoloUsuario"'
          - 'gradle clean test -Dcucumber.filter.tags="@LoginVacio"'
          - 'gradle clean test -Dcucumber.filter.tags="@CreacionDeUsuarioAdmin"'
          - 'gradle clean test -Dcucumber.filter.tags="@ModificarUsuarioAdmin"'
          - 'gradle clean test -Dcucumber.filter.tags="@Eliminarusuario"'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar Google Chrome y ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Verificar instalaci贸n
        run: |
          google-chrome --version
          chromedriver --version

      - name: Pre ejecuci贸n
        run: gradle clean clearReports

      - name: Instalaci贸n
        run: gradle clean build -x test

      - name: Ejecuci贸n
        run: ${{ matrix.command }}