jobs:
  integration-e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - 'gradle clean test -Dcucumber.filter.tags="@LoginErroneo"'
          - 'gradle clean test -Dcucumber.filter.tags="@LoginSoloUsuario"'
          - 'gradle clean test -Dcucumber.filter.tags="@LoginVacio"'
          - 'gradle clean test -Dcucumber.filter.tags="@CreacionDeUsuarioAdmin"'
          - 'gradle clean test -Dcucumber.filter.tags="@ModificarUsuarioAdmin"'
          - 'gradle clean test -Dcucumber.filter.tags="@Eliminarusuario"'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Instalar ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Verificar instalaci贸n de ChromeDriver
        run: chromedriver --version

      - name: Pre ejecuci贸n
        run: gradle clean clearReports

      - name: Instalaci贸n
        run: gradle clean build -x test

      - name: Ejecuci贸n
        run: ${{ matrix.command }}
